header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: RisingWave Labs

  paths:
    - "src/**/*.rs"
    - "src/**/*.py"
    - "src/**/*.html"
    - "dashboard/**/*.js"
    - "dashboard/**/*.ts"
    - "java/**/*.java"
    - "java/**/*.py"

  paths-ignore:
    - "**/gen/**"
    - "**/*.d.ts"
    - "src/sqlparser/**/*.rs"
    - "java/connector-node/risingwave-source-cdc/src/main/java/com/risingwave/connector/cdc/debezium/internal/*.java"

  comment: on-failure
