[package]
name = "risingwave_bench"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
async-trait = "0.1"
aws-config = { workspace = true }
aws-sdk-s3 = { workspace = true }
aws-smithy-http = { workspace = true }
bcc = { version = "0.0.33", optional = true }
bytes = "1"
bytesize = { version = "1", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
futures = { version = "0.3", default-features = false, features = ["alloc"] }
hdrhistogram = "7"
itertools = "0.11"
libc = "0.2"
opentelemetry = { version = "0.20", default-features = false, features = ["rt-tokio"], optional = true }
parking_lot = "0.12"
prometheus = { version = "0.13", features = ["process"] }
rand = "0.8"
risingwave_common = { workspace = true }
risingwave_rt = { workspace = true, optional = true }
risingwave_storage = { workspace = true }
serde = { version = "1", features = ["derive"] }
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "fs",
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
] }
tokio-stream = "0.1"
toml = "0.7"
tracing = "0.1"
tracing-subscriber = "0.3.17"

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../workspace-hack" }

[target.'cfg(target_os = "linux")'.dependencies]
nix = { version = "0.26", features = ["fs", "mman"] }

[[bin]]
name = "s3-bench"
path = "s3_bench/main.rs"

[features]
bpf = ["bcc", "risingwave_storage/bpf"]
trace = ["opentelemetry", "risingwave_rt", "tracing/release_max_level_trace"]

[lints]
workspace = true
