[package]
name = "risingwave_hummock_test"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.cargo-machete]
ignored = ["workspace-hack"]

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-hack"]

[dependencies]
async-trait = "0.1"
bytes = { version = "1" }
clap = { version = "4", features = ["derive"] }
fail = "0.5"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
futures-async-stream = "0.2"
itertools = "0.11"
parking_lot = "0.12"
rand = "0.8"
risingwave_common = { workspace = true }
risingwave_common_service = { workspace = true }
risingwave_hummock_sdk = { workspace = true }
risingwave_hummock_trace = { workspace = true }
risingwave_meta = { workspace = true, features = ["test"] }
risingwave_object_store = { workspace = true }
risingwave_pb = { workspace = true }
risingwave_rpc_client = { workspace = true }
risingwave_storage = { workspace = true, features = ["test"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "0.2", package = "madsim-tokio" }

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../../workspace-hack" }

[dev-dependencies]
criterion = { workspace = true, features = ["async_futures"] }
expect-test = "1"
futures = { version = "0.3", default-features = false, features = [
    "alloc",
    "executor",
] }

futures-async-stream = "0.2"
risingwave_test_runner = { workspace = true }
serial_test = "2.0"
sync-point = { path = "../../utils/sync-point" }

[features]
failpoints = ["risingwave_storage/failpoints"]
sync_point = ["sync-point/sync_point"]
test = []

[[bench]]
name = "bench_hummock_iter"
harness = false
required-features = ["test"]

[[bin]]
name = "replay"
path = "src/bin/replay/main.rs"

[lints]
workspace = true
