[package]
name = "risingwave_rpc_client"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["workspace-hack"]

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-hack"]

[dependencies]
anyhow = "1"
async-trait = "0.1"
easy-ext = "1"
either = "1.9.0"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
hyper = "0.14"
itertools = "0.11.0"
lru = "0.10.1"
rand = "0.8"
risingwave_common = { workspace = true }
risingwave_hummock_sdk = { workspace = true }
risingwave_pb = { workspace = true }
static_assertions = "1"
thiserror = "1"
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
] }
tokio-retry = "0.3"
tokio-stream = "0.1"
tonic = { workspace = true }
tower = "0.4"
tracing = "0.1"
url = "2.4.1"

[target.'cfg(not(madsim))'.dependencies]
moka = { version = "0.11", features = ["future"] }
workspace-hack = { path = "../workspace-hack" }

[lints]
workspace = true
