name: PR for release branch
on:
  pull_request:
    branches:
      - main
    types: ["closed", "labeled"]

jobs:
  release_pull_request_1_1:
    if: "contains(github.event.pull_request.labels.*.name, 'need-cherry-pick-v1.1')  &&  github.event.pull_request.merged == true"
    runs-on: ubuntu-latest
    name: release_pull_request
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Create PR to branch
        uses: risingwavelabs/github-action-cherry-pick@master
        with:
          pr_branch: 'v1.1-rc'
          pr_labels: 'cherry-pick'
          pr_body: ${{ format('Cherry picking \#{0} onto branch v1.1-rc', github.event.number) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release_pull_request_1_2:
    if: "contains(github.event.pull_request.labels.*.name, 'need-cherry-pick-v1.2')  &&  github.event.pull_request.merged == true"
    runs-on: ubuntu-latest
    name: release_pull_request
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Create PR to branch
        uses: risingwavelabs/github-action-cherry-pick@master
        with:
          pr_branch: 'v1.2-rc'
          pr_labels: 'cherry-pick'
          pr_body: ${{ format('Cherry picking \#{0} onto branch v1.2-rc', github.event.number) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

