name: Deploy Developer Docs

on:
  push:
    branches:
      - main

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  RUSTDOCFLAGS: "--cfg docsrs --markdown-css rust.css --markdown-no-toc --index-page /home/runner/work/risingwave/risingwave/docs/rustdoc/index.md -Zunstable-options"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust toolchain
        run: rustup show
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make build-essential cmake protobuf-compiler curl openssl libssl-dev libsasl2-dev libcurl4-openssl-dev pkg-config postgresql-client tmux lld
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3
        with:
          version: "v0.5.2"
      - name: build rustdocs
        run: |
          cargo doc --workspace --no-deps --document-private-items
          cp docs/rustdoc/rust.css target/doc/rust.css

          mkdir artifact
          cp -R target/doc/* artifact
      - name: Install cargo-docset
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-docset
      - name: build docsets
        run: |
          cargo docset --no-clean --docset-name RisingWave
          tar -czf risingwave.docset.tgz target/docset/risingwave.docset

          echo "<entry>
          <version>$(date -u +%Y-%m-%dT%H:%M:%SZ)</version>
          <url>https://risingwavelabs.github.io/risingwave/risingwave.docset.tgz</url>
          </entry>" > RisingWave.xml

          cp -t artifact "risingwave.docset.tgz" "RisingWave.xml"
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: artifact

  deploy:
    needs: build
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
